version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: testdb
    working_dir: /application
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: testpass
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
